help:  ##print this message
	@fgrep -h '##' $(MAKEFILE_LIST) | fgrep -v fgrep | sed -e 's/\\$$//' | sed -e 's/##//'
frontend:	##install frontend component
	@echo installing frontend
cart:	##install cart component
	@echo installing cart
catalogue:
	@echo installing catalogue
payment:	##install payment component
	@echo installing payment
shipping:	##install shipping component
	@echo installing shipping
user:	##install user component
	@echo installing user
mongodb:	##install mongodb component
	@echo installing mongodb
mysql:	##install mysql component
	@echo installing mysql
rabbitmq:	##install rabbitmq component
	@echo installing rabbitmq
redis:
	@echo installing redis
