help:  ##print this message
	@fgrep -h '##' $(MAKEFILE_LIST) | fgrep -v fgrep | sed -e 's/\\$$//' | sed -e 's/##//'
frontend: ##install frontend component
	@echo installing frontend
cart:
	@echo installing cart
catalogue:
	@echo installing catalogue
payment:
	@echo installing payment
shipping:
	@echo installing shipping
user:
	@echo installing user
mongodb:
	@echo installing mongodb
mysql:
	@echo installing mysql
rabbitmq:
	@echo installing rabbitmq
redis:
	@echo installing redis
